# Your Name or Company
title: PhD Scholarships

# Description of your website. This is used for social sharing.
description:  PhD recruitment Ads

# A brief blurb about yourself
content:  PhD Position in Artificial Intelligence for Timber Structure Design Optimisation 





# Add your social links
social:
  - platform: github
    url: https://github.com/brianmaierjr
  - platform: facebook
    url: https://facebook.com/brianmaierjr
  - platform: twitter
    url: https://twitter.com/brianmaierjr
  - platform: linkedin
    url: brianmaierjr

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: ai.png
#google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
# half_side: right

# Full layout
full_text_position: right # left, right or center
